name: GitHub Pages

on:
  push:
    branches:
    - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set Directory
      run: cd frontend

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.16'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
